import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { ViewTransitions } from "next-view-transitions";
import { Toaster } from 'sonner';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  // const post = await fetchPost({userId: "clv7thhs80000n9qgw4nua1ba"})
  // console.log(post)
  return (
    <SessionProvider session={session}>
      <ViewTransitions>
        <html lang="en">
          <body className={inter.className}>
            {children}
            <Toaster position="top-center" richColors />
            </body>
        </html>
      </ViewTransitions>
    </SessionProvider>
  );
}
